---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile-clone
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: azurefile-csi
  dataSource:
    kind: PersistentVolumeClaim
    name: pvc-azurefile
